version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8-alpine
    steps:
      - checkout
      - restore_cache:
          key: maven
      - run: mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: maven
      - codecov/upload:
          file: jacoco/*