version: 2

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8-alpine
    steps:
      - checkout
      - restore_cache:
          key: maven
      - run: mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: maven